### ISSUE TITLE
No "exports" main defined in @sveltejs/adapter-node/package.json

### ISSUE THREAD

**Issue by jakemckown** [tejasag/sveltetron-9000#3]
When I run `yarn dev`, I get this error:

```
$ svelte-kit dev
svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module. See https://kit.svelte.dev/docs#configuration for an example
No "exports" main defined in ...\sveltetron-9000\node_modules\@sveltejs\adapter-node\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ...\sveltetron-9000\node_modules\@sveltejs\adapter-node\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (...\sveltetron-9000\svelte.config.cjs:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
error Command failed with exit code 1.
```

When I run `yarn storybook`, I get a similar error:

```
$ start-storybook -p 6006
info @storybook/svelte v6.2.9
info
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ...\sveltetron-9000\node_modules\@sveltejs\adapter-node\package.json
ERR!     at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
ERR!     at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
ERR!     at resolveExports (internal/modules/cjs/loader.js:432:36)
ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (...\sveltetron-9000\svelte.config.cjs:2:14)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (...\sveltetron-9000\.storybook\main.cjs:12:19)
ERR!  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ...\sveltetron-9000\node_modules\@sveltejs\adapter-node\package.json
ERR!     at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
ERR!     at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
ERR!     at resolveExports (internal/modules/cjs/loader.js:432:36)
ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (...\sveltetron-9000\svelte.config.cjs:2:14)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (...\sveltetron-9000\.storybook\main.cjs:12:19) {
ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
```

I'm using Windows 10 64-bit, Node 14.16.0, and Yarn 1.22.4.

**Comment by raghav-kukreti** [comment]
As the error says, `svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module`, the template is outdated.
